In [3]:
a = list(range(1000000))

In [18]:
%time a2 = [i*2 for i in a]

Wall time: 82.5 ms


In [3]:
import numpy as np

In [9]:
na = np.array(range(1000000))

In [10]:
%time na2 = na * 2

Wall time: 2.97 ms


In [21]:
v = np.array([[1, 2], [3, 4]])

In [22]:
v

array([[1, 2],
       [3, 4]])

In [23]:
type(v)

numpy.ndarray

In [24]:
ara = np.arange(1, 10)

In [25]:
ara

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.linspace(1, 10, 15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [5]:
a = np.arange(10).reshape(2, -1)

In [46]:
a

(array([0, 1, 1, 1, 1, 1], dtype=int64),
 array([4, 0, 1, 2, 3, 4], dtype=int64))

In [50]:
a

(array([0, 1, 1, 1, 1, 1], dtype=int64),
 array([4, 0, 1, 2, 3, 4], dtype=int64))

In [6]:
np.where(a > 2)

(array([0, 0, 1, 1, 1, 1, 1], dtype=int64),
 array([3, 4, 0, 1, 2, 3, 4], dtype=int64))

***

#### 数组属性

In [7]:
v = np.zeros(10)

In [13]:
m = np.ones((3, 4), dtype=int)

In [9]:
v.shape

(10,)

In [10]:
m.shape

(3, 4)

In [11]:
m.size

12

In [14]:
m.dtype

dtype('int32')

In [17]:
m[0, 0] = 2

In [18]:
m

array([[2, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
m = np.array([1, 2, 3.])

In [20]:
m

array([1., 2., 3.])

In [21]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.logspace(1, 10, 10, base=np.e)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [25]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [26]:
np.diag([1, 2, 3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [27]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.random.rand(3, 5)

array([[0.05187251, 0.82044829, 0.01852016, 0.32702251, 0.33269794],
       [0.77831151, 0.16087581, 0.81991519, 0.6521711 , 0.37890228],
       [0.26475697, 0.84972259, 0.27421964, 0.79889839, 0.07596032]])

In [60]:
m = np.arange(18).reshape(2, 3, 3)

In [61]:
m

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [62]:
m[:, 1:3, :1]

array([[[ 3],
        [ 6]],

       [[12],
        [15]]])

In [63]:
m[:,0,:] = -1

In [64]:
m

array([[[-1, -1, -1],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[-1, -1, -1],
        [12, 13, 14],
        [15, 16, 17]]])

In [70]:
m[:,:,0]

array([[-1,  3,  6],
       [-1, 12, 15]])

In [71]:
mt = m[:,:,0]

In [72]:
mt[mt>5]

array([ 6, 12, 15])

In [73]:
np.ones((3, 5), dtype=bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [74]:
a = np.linspace(1, 5, 10)

In [75]:
a.reshape(5, 2)

array([[1.        , 1.44444444],
       [1.88888889, 2.33333333],
       [2.77777778, 3.22222222],
       [3.66666667, 4.11111111],
       [4.55555556, 5.        ]])

In [80]:
m = np.arange(10).reshape(2, 5)

In [77]:
m[m & 1 == 1] = -1

In [78]:
m

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [81]:
m[m & 1 == 1]

array([1, 3, 5, 7, 9])

In [82]:
m, n = np.arange(10), np.arange(1, 15, 3)

In [83]:
np.intersect1d(m, n)

array([1, 4, 7])

In [84]:
np.setdiff1d(m, n)

array([0, 2, 3, 5, 6, 8, 9])

In [85]:
m = np.arange(10).reshape(2, 5)

In [86]:
m[(m > 2) & (m < 7)]

array([3, 4, 5, 6])

In [87]:
m[:,[1, 0, 2, 3, 4]]

array([[1, 0, 2, 3, 4],
       [6, 5, 7, 8, 9]])

In [88]:
m[:, [1, 0, 2, 4, 3]]

array([[1, 0, 2, 4, 3],
       [6, 5, 7, 9, 8]])

In [89]:
m[::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [90]:
np.random.seed(100)

In [91]:
np.random.randint(5, 10, (3, 5)) + np.random.rand(3, 5)

array([[5.20920212, 5.18532822, 8.10837689, 5.21969749, 7.97862378],
       [9.81168315, 7.17194101, 7.81622475, 7.27407375, 7.43170418],
       [6.94002982, 5.81764938, 5.33611195, 9.17541045, 8.37283205]])

In [92]:
np.random.seed(100)

In [93]:
np.random.randint(5, 10, (3, 5)) + np.random.random((3, 5))

array([[5.20920212, 5.18532822, 8.10837689, 5.21969749, 7.97862378],
       [9.81168315, 7.17194101, 7.81622475, 7.27407375, 7.43170418],
       [6.94002982, 5.81764938, 5.33611195, 9.17541045, 8.37283205]])

### 进阶高效

In [2]:
import tensorflow as tf

In [3]:
tf.__file__

'C:\\Users\\zff\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py'